import React, {
  useCallback,
  useEffect,
  useRef,
  useState,
  type ComponentProps,
} from 'react';
import { Pressable, View } from 'react-native';
import RNMapView, { Marker, Polyline, type LatLng } from 'react-native-maps';
import * as Location from 'expo-location';
import LocationModal from '@/components/location-modal';
import useLocationPermission from '@/hooks/useLocationPermission';
import MapView from '@/components/map-view';
import {
  useRouteCalculation,
  type RouteStop,
} from '@/hooks/useRouteCalculation';
import RouteControlPanel from '@/components/route/route-control-panel';
import RouteLoadingOverlay from '@/components/route/route-loading-overlay';
import RoutePreferencesModal, {
  type RoutePreferences,
} from '@/components/route/route-preferences-modal';
import useMonumentSuggestions from '@/hooks/useMonumentSuggestions';
import {
  MonumentSuggestionList,
  MonumentSuggestionMarkers,
} from '@/components/monument-suggestions';
import CreateGroupRouteButton from '@/components/group-routes/create-group-route-button';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';

export default function RouteScreen() {
  const { granted, visibility, onAllow, onLater } = useLocationPermission();
  const { minKm, maxKm } = useLocalSearchParams<{
    minKm?: string;
    maxKm?: string;
  }>();

  const mapRef = useRef<RNMapView>(null);
  const [start, setStart] = useState<LatLng | null>(null);
  const [monumentStops, setMonumentStops] = useState<RouteStop[]>([]);
  const [preferencesModalVisible, setPreferencesModalVisible] = useState(false);
  const autoGeneratedRef = useRef(false);

  const handleRouteCalculated = useCallback((coords: LatLng[]) => {
    mapRef.current?.fitToCoordinates(coords, {
      edgePadding: { top: 80, right: 50, bottom: 120, left: 50 },
      animated: true,
    });
  }, []);

  const {
    waypoints,
    route,
    loop,
    activeRoute,
    error,
    loading,
    isGeneratingRoute,
    statusText,
    maxWaypoints,
    generateRoute,
    generateLoop,
    addWaypoint,
    resetRoute,
  } = useRouteCalculation({
    start,
    useUserLocationAsStart: true,
    onRouteCalculated: handleRouteCalculated,
    stops: monumentStops,
  });

  const routeKey = loop
    ? `loop-${loop.bearing}`
    : waypoints.length > 0
      ? JSON.stringify(waypoints)
      : '';

  const monuments = useMonumentSuggestions(
    activeRoute,
    routeKey,
    setMonumentStops
  );

  // Fetch initial location when permission is granted
  useEffect(() => {
    if (!granted) return;

    let cancelled = false;

    (async () => {
      try {
        // Step 1: Instantly retrieve cached location if available
        const lastKnown = await Location.getLastKnownPositionAsync({
          maxAge: 60000,
        });

        if (!cancelled && lastKnown) {
          const cachedLoc = {
            latitude: lastKnown.coords.latitude,
            longitude: lastKnown.coords.longitude,
          };

          setStart(cachedLoc);
          mapRef.current?.animateToRegion({
            ...cachedLoc,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
          });
        }

        // Step 2: Concurrently fetch fresh position with balanced accuracy for fast resolution
        const fresh = await Location.getCurrentPositionAsync({
          accuracy: Location.Accuracy.Balanced,
        });

        if (!cancelled) {
          const freshLoc = {
            latitude: fresh.coords.latitude,
            longitude: fresh.coords.longitude,
          };

          setStart(freshLoc);
          mapRef.current?.animateToRegion({
            ...freshLoc,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
          });
        }
      } catch (e) {
        console.warn('Location error:', e instanceof Error ? e.message : e);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [granted]);

  useEffect(() => {
    if (start && minKm && maxKm && !autoGeneratedRef.current) {
      const min = parseFloat(minKm);
      const max = parseFloat(maxKm);
      if (!isNaN(min) && !isNaN(max)) {
        autoGeneratedRef.current = true;
        generateLoop({ minKm: min, maxKm: max });
      }
    }
  }, [start, minKm, maxKm, generateLoop]);

  const onMapPress: ComponentProps<typeof MapView>['onPress'] = (e) => {
    const action = (e.nativeEvent as { action?: string })?.action;
    if (action === 'marker-press' || action === 'callout-press') return;
    if (loop || activeRoute) return;
    addWaypoint(e.nativeEvent.coordinate);
  };

  const goToMe = async () => {
    try {
      const { coords } = await Location.getCurrentPositionAsync({});
      mapRef.current?.animateCamera({
        center: { latitude: coords.latitude, longitude: coords.longitude },
        zoom: 16,
      });
    } catch (e) {
      console.warn('Location error:', e instanceof Error ? e.message : e);
    }
  };

  return (
    <View className='flex-1'>
      <LocationModal
        visible={visibility}
        onAllow={onAllow}
        onLater={onLater}
      />

      <Pressable
        onPress={goToMe}
        className='absolute top-21 right-4 z-10 size-10 items-center justify-center rounded-full bg-white shadow-lg'>
        <Ionicons
          name='locate'
          size={24}
          color='#2563eb'
        />
      </Pressable>

      <MapView
        ref={mapRef}
        permission={granted}
        onPress={onMapPress}>
        {waypoints.map((w, i) => (
          <Marker
            key={`${w.latitude}-${w.longitude}-${i}`}
            coordinate={w}
            title={
              w.name ||
              (maxWaypoints === 1 ? 'Destination' : `Waypoint ${i + 1}`)
            }
            description={w.description}
          />
        ))}

        <MonumentSuggestionMarkers {...monuments} />

        <Polyline
          coordinates={route?.coords ?? []}
          strokeWidth={route ? 4 : 0}
          strokeColor={route ? '#2563eb' : 'transparent'}
        />

        <Polyline
          coordinates={loop?.coords ?? []}
          strokeWidth={loop ? 4 : 0}
          strokeColor={loop ? '#16a34a' : 'transparent'}
        />
      </MapView>

      <RouteControlPanel
        statusText={statusText}
        isError={!!error}
        disabled={loading || !start}
        showGeneratorButton={!activeRoute}
        showResetButton={Boolean(activeRoute)}
        onOpenPreferences={() => setPreferencesModalVisible(true)}
        onReset={() => {
          setMonumentStops([]);
          monuments.clear();
          resetRoute();
        }}>
        <MonumentSuggestionList {...monuments} />
        {activeRoute && (
          <CreateGroupRouteButton
            route={activeRoute}
            stops={monumentStops}
          />
        )}
      </RouteControlPanel>

      <RoutePreferencesModal
        visible={preferencesModalVisible}
        onClose={() => setPreferencesModalVisible(false)}
        onConfirm={(preferences: RoutePreferences) => {
          setMonumentStops([]);
          monuments.clear();
          generateRoute(preferences);
        }}
      />

      <RouteLoadingOverlay
        loading={isGeneratingRoute}
        hasRoute={Boolean(activeRoute)}
        loadingMessage={statusText}
      />
    </View>
  );
}
